package com.guilhermepereira.springchess.game.engines;

import com.guilhermepereira.springchess.game.Board;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class StockfishEngineTest {

	@Test
	@DisplayName("Testing if suggested move is being generated by stockfish")
	public void shouldSuggestMove() {
		Board board = new Board();
		board.initialize();

		StockfishEngine stockfishEngine = new StockfishEngine();
		stockfishEngine.initialize();

		assertNotNull(stockfishEngine.getBestMove(board));

		stockfishEngine.finish();
	}
}